### ISSUE TITLE
Equipment for Adversaries should include ships and creatures

### ISSUE THREAD

**Issue by bknowles** [karrde/ffg_swrpg#31] opened 2014-06-25 21:05 UTC
The Smuggler Baron in the CRB has a YT-2400 as equipment, and there is currently no way to reflect this in the FFG SWRPG Index.  Or, you can list it, but you can't link it to the actual entry for the YT-2400 ship.

Likewise, Reom (from BtR) is supposed to have a "pet bogwing" as one of his "pieces of equipment", but this seems to be a creature of some sort that is not detailed anywhere else that I can find.  Still, it would be good to be able to properly reference this.

**Comment by karrde** [comment] 2016-03-30 12:55
Duplicate of #1

**Closed by karrde** 2016-03-30 12:55 UTC
Labels: duplicate
